name: Deploy
on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository

        steps:
            - name: Clone repository
              uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.12.2
            - run: npm install -g pnpm
            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - run: deno test -A --unstable-net
            - name: Build step
              run: |
                  cd static
                  npx -y cnpm install
                  npm run build
                  cd ../

            - name: Upload to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: "deno-dns-over-https-server"
                  entrypoint: "./main.tsx"
                  root: ""
